protocol/serial: add serial protocol implementation
csssuf/rust-uefi pull request #13
Opened 2017-07-01 00:28 UTC by csssuf

Also pulls in bitflags as a dependency in order to represent the ControlBits structure.

2017-07-04 05:09 UTC, bgilbert requested changes

2017-07-04 05:09 UTC, bgilbert commented on src/protocol/serial.rs
> +                Status::Success => Ok(Some((buf, new_length))),
I assume you're returning `buf` for chaining purposes?  If so, is that a sufficient reason to do it?

2017-07-04 05:09 UTC, bgilbert commented on src/protocol/serial.rs
> +                str::from_utf8_unchecked(slice::from_raw_parts(bytes, read_length))
Is this an in-place conversion?  If not, you're leaking the buffer.

The user's charset is not necessarily UTF-8 and there's nothing preventing them from emitting the high bit, so `unchecked` is not safe.

2017-07-05 21:00 UTC, csssuf commented on src/protocol/serial.rs
> +                Status::Success => Ok(Some((buf, new_length))),
It is for chaining, yes. I think it's slightly cleaner to do so but I'm not overly attached to it, is there a reason not to?

2017-07-05 21:00 UTC, csssuf commented on src/protocol/serial.rs
> +                str::from_utf8_unchecked(slice::from_raw_parts(bytes, read_length))
The conversion is in-place, so there's no leak. I think the best approach here might be to just expose a `read_bytes` which returns a slice of bytes instead, and let library consumers do with the bytes what they want.

2017-07-10 18:09 UTC, bgilbert requested changes

2017-07-10 18:09 UTC, bgilbert commented on src/protocol/serial.rs
> +                let attr = protocol.set_attributes(None, None, Some(timeout), None, None, None);
Presumably we need to support non-default configuration?

2017-07-10 18:09 UTC, bgilbert commented on src/protocol/serial.rs
> +        let attr_status = self.raw_protocol.set_attributes(None, None, Some(self.timeout), None, None, None);
Needs a comment explaining why we do this before every I/O.

2017-07-18 22:06 UTC, bgilbert approved these changes

2017-07-18 22:06 UTC, bgilbert commented on src/protocol/serial.rs
> +        // GRUB sets the attributes on the serial device on each read or write, so we will too.
We're also doing it because it avoids a specific problem.  Please document what that is.

2017-07-19 18:12 UTC, merged